[project]
name = "peakrdl-sv"
description = "A SystemRDL exporter for SystemVerilog "
authors = [{ name = "Shareef Jalloq" }]
readme = "README.md"
keywords = [
    "SystemRDL",
    "exporter",
    "SystemVerilog",
    "Verilog",
    "Register File",
    "Register",
    "CSR",
]
requires-python = ">=3.9"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = ["systemrdl-compiler", "peakrdl", "mako"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pre-commit", "numpy", "cocotb", "cocotb-bus", "pytest"]

[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
sv-exporter = "peakrdl_sv.main:main"

[tool.setuptools_scm]

[tool.black]
line-length = 88
experimental-string-processing = true

[project.entry-points."peakrdl.exporters"]
sv = "peakrdl_sv.__peakrdl__:VerilogExporter"
py = "peakrdl_sv.__peakrdl__:PythonExporter"
