# Copyright Nu Quantum Ltd
# Copyright 2026 Shareef Jalloq
# SPDX-License-Identifier: MIT
#
# Auto-generated by peakrdl-sv
<%
  lname = block.inst_name[0].upper() + block.inst_name[1:].lower()
  registers  = block.get_registers()
%>\

class ${lname}RegMap:

    # Register address offsets
    % for r in registers:
<%
    if r.is_wide:
      values = []
      params = []
      for i in range(r.subregs):
        values.append(f"0x{r.absolute_address+(i*r.addressincr):X}")
        params.append(f"{r.path().upper()}_{i}")

    else:
      values = [f"0x{r.absolute_address:X}"]
      params = [f"{r.path().upper()}"]
%>
    % for p,v in zip(params, values):
    ${p} = ${v}
    % endfor
    % endfor
